stepsSpl<-split(data$steps, data$dates$yday)
sumStepsPerDay<-sapply(stepsSpl, sum, na.rm=TRUE)
plot(uniqueDates, sumStepsPerDay, main="Histogram of steps per day", xlab="Date", ylab="Frequency", type="h", lwd=4, col="blue")
meanStepsPerDay <- sapply(stepsSpl, mean, na.rm=TRUE)
meanDataFrame <- data.frame(date=uniqueDates, meanStepsPerDay=meanStepsPerDay, row.names=NULL)
cat("Mean steps per day:", "\n")
print(meanDataFrame)
medianStepsPerDay <- sapply(stepsSpl, median, na.rm=TRUE)
medianDataFrame <- data.frame(date=uniqueDates, medianStepsPerDay=medianStepsPerDay, row.names=NULL)
cat("Median steps per day:", "\n")
print(medianDataFrame)